package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Actividades generated by hbm2java
 */
public class Actividades implements java.io.Serializable {

	private String idActividad;
	private Empresas empresas;
	private Project project;
	private FactoresIncumplimiento factoresIncumplimiento;
	private Usuarios usuarios;
	private Date fechaAsignada;
	private Date fechaComienzo;
	private Date fechaTermino;
	private Date fechaActualizada;

	public Actividades() {
	}

	public Actividades(String idActividad, Empresas empresas, Project project,
			FactoresIncumplimiento factoresIncumplimiento, Usuarios usuarios) {
		this.idActividad = idActividad;
		this.empresas = empresas;
		this.project = project;
		this.factoresIncumplimiento = factoresIncumplimiento;
		this.usuarios = usuarios;
	}

	public Actividades(String idActividad, Empresas empresas, Project project,
			FactoresIncumplimiento factoresIncumplimiento, Usuarios usuarios, Date fechaAsignada, Date fechaComienzo,
			Date fechaTermino, Date fechaActualizada) {
		this.idActividad = idActividad;
		this.empresas = empresas;
		this.project = project;
		this.factoresIncumplimiento = factoresIncumplimiento;
		this.usuarios = usuarios;
		this.fechaAsignada = fechaAsignada;
		this.fechaComienzo = fechaComienzo;
		this.fechaTermino = fechaTermino;
		this.fechaActualizada = fechaActualizada;
	}

	public String getIdActividad() {
		return this.idActividad;
	}

	public void setIdActividad(String idActividad) {
		this.idActividad = idActividad;
	}

	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public FactoresIncumplimiento getFactoresIncumplimiento() {
		return this.factoresIncumplimiento;
	}

	public void setFactoresIncumplimiento(FactoresIncumplimiento factoresIncumplimiento) {
		this.factoresIncumplimiento = factoresIncumplimiento;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFechaAsignada() {
		return this.fechaAsignada;
	}

	public void setFechaAsignada(Date fechaAsignada) {
		this.fechaAsignada = fechaAsignada;
	}

	public Date getFechaComienzo() {
		return this.fechaComienzo;
	}

	public void setFechaComienzo(Date fechaComienzo) {
		this.fechaComienzo = fechaComienzo;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public Date getFechaActualizada() {
		return this.fechaActualizada;
	}

	public void setFechaActualizada(Date fechaActualizada) {
		this.fechaActualizada = fechaActualizada;
	}

	@Override
	public String toString() {
		return "Actividades [idActividad=" + idActividad + ", empresas=" + empresas + ", project=" + project
				+ ", factoresIncumplimiento=" + factoresIncumplimiento + ", usuarios=" + usuarios + ", fechaAsignada="
				+ fechaAsignada + ", fechaComienzo=" + fechaComienzo + ", fechaTermino=" + fechaTermino
				+ ", fechaActualizada=" + fechaActualizada + "]";
	}

}
