package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

/**
 * Codigos generated by hbm2java
 */
public class Codigos implements java.io.Serializable {

	private Integer id;
	private String tabla;
	private Integer longitud;
	private String prefijo;
	private String sufijo;

	public Codigos() {
	}

	public Codigos(String tabla, Integer longitud, String prefijo, String sufijo) {
		this.tabla = tabla;
		this.longitud = longitud;
		this.prefijo = prefijo;
		this.sufijo = sufijo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	public Integer getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Integer longitud) {
		this.longitud = longitud;
	}

	public String getPrefijo() {
		return this.prefijo;
	}

	public void setPrefijo(String prefijo) {
		this.prefijo = prefijo;
	}

	public String getSufijo() {
		return this.sufijo;
	}

	public void setSufijo(String sufijo) {
		this.sufijo = sufijo;
	}

}
