package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

/**
 * Comentarios generated by hbm2java
 */
public class Comentarios implements java.io.Serializable {

	private Integer idComentario;
	private Usuarios usuarios;
	private String comentario;

	public Comentarios() {
	}

	public Comentarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Comentarios(Usuarios usuarios, String comentario) {
		this.usuarios = usuarios;
		this.comentario = comentario;
	}

	public Integer getIdComentario() {
		return this.idComentario;
	}

	public void setIdComentario(Integer idComentario) {
		this.idComentario = idComentario;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
