package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas implements java.io.Serializable {

	private String idEmpresa;
	private String razonSocial;
	private String correo;
	private Set<Actividades> actividadeses = new HashSet<Actividades>(0);

	public Empresas() {
	}

	public Empresas(String idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public Empresas(String idEmpresa, String razonSocial, String correo, Set<Actividades> actividadeses) {
		this.idEmpresa = idEmpresa;
		this.razonSocial = razonSocial;
		this.correo = correo;
		this.actividadeses = actividadeses;
	}

	public String getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(String idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Set<Actividades> getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(Set<Actividades> actividadeses) {
		this.actividadeses = actividadeses;
	}

}
