package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FactoresIncumplimiento generated by hbm2java
 */
public class FactoresIncumplimiento implements java.io.Serializable {

	private String idFactorIncumplimiento;
	private String nombreFactorIncumplimiento;
	private Set<Actividades> actividadeses = new HashSet<Actividades>(0);

	public FactoresIncumplimiento() {
	}

	public FactoresIncumplimiento(String idFactorIncumplimiento) {
		this.idFactorIncumplimiento = idFactorIncumplimiento;
	}

	public FactoresIncumplimiento(String idFactorIncumplimiento, String nombreFactorIncumplimiento,
			Set<Actividades> actividadeses) {
		this.idFactorIncumplimiento = idFactorIncumplimiento;
		this.nombreFactorIncumplimiento = nombreFactorIncumplimiento;
		this.actividadeses = actividadeses;
	}

	public String getIdFactorIncumplimiento() {
		return this.idFactorIncumplimiento;
	}

	public void setIdFactorIncumplimiento(String idFactorIncumplimiento) {
		this.idFactorIncumplimiento = idFactorIncumplimiento;
	}

	public String getNombreFactorIncumplimiento() {
		return this.nombreFactorIncumplimiento;
	}

	public void setNombreFactorIncumplimiento(String nombreFactorIncumplimiento) {
		this.nombreFactorIncumplimiento = nombreFactorIncumplimiento;
	}

	public Set<Actividades> getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(Set<Actividades> actividadeses) {
		this.actividadeses = actividadeses;
	}

}
