package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Losas generated by hbm2java
 */
public class Losas implements java.io.Serializable {

	private String idLosa;
	private Partida partida;
	private String nombre;
	private Date fechaProgramada;
	private Date fechaTermino;

	public Losas() {
	}

	public Losas(String idLosa, Partida partida) {
		this.idLosa = idLosa;
		this.partida = partida;
	}

	public Losas(String idLosa, Partida partida, String nombre, Date fechaProgramada, Date fechaTermino) {
		this.idLosa = idLosa;
		this.partida = partida;
		this.nombre = nombre;
		this.fechaProgramada = fechaProgramada;
		this.fechaTermino = fechaTermino;
	}

	public String getIdLosa() {
		return this.idLosa;
	}

	public void setIdLosa(String idLosa) {
		this.idLosa = idLosa;
	}

	public Partida getPartida() {
		return this.partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaProgramada() {
		return this.fechaProgramada;
	}

	public void setFechaProgramada(Date fechaProgramada) {
		this.fechaProgramada = fechaProgramada;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

}
