package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida implements java.io.Serializable {

	private String idPartida;
	private Reportes reportes;
	private String nombre;
	private Set<Losas> losases = new HashSet<Losas>(0);

	public Partida() {
	}

	public Partida(String idPartida, Reportes reportes) {
		this.idPartida = idPartida;
		this.reportes = reportes;
	}

	public Partida(String idPartida, Reportes reportes, String nombre, Set<Losas> losases) {
		this.idPartida = idPartida;
		this.reportes = reportes;
		this.nombre = nombre;
		this.losases = losases;
	}

	public String getIdPartida() {
		return this.idPartida;
	}

	public void setIdPartida(String idPartida) {
		this.idPartida = idPartida;
	}

	public Reportes getReportes() {
		return this.reportes;
	}

	public void setReportes(Reportes reportes) {
		this.reportes = reportes;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Losas> getLosases() {
		return this.losases;
	}

	public void setLosases(Set<Losas> losases) {
		this.losases = losases;
	}

}
