package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Proyectos generated by hbm2java
 */
public class Proyectos implements java.io.Serializable {

	private String idProyecto;
	private String nombreProyecto;
	private Boolean activo;
	private Boolean finalizado;
	private Set<Reportes> reporteses = new HashSet<Reportes>(0);
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<UsuariosProyectos> usuariosProyectoses = new HashSet<UsuariosProyectos>(0);

	public Proyectos() {
	}

	public Proyectos(String idProyecto) {
		this.idProyecto = idProyecto;
	}

	public Proyectos(String idProyecto, String nombreProyecto, Boolean activo, Boolean finalizado,
			Set<Reportes> reporteses, Set<Project> projects, Set<UsuariosProyectos> usuariosProyectoses) {
		this.idProyecto = idProyecto;
		this.nombreProyecto = nombreProyecto;
		this.activo = activo;
		this.finalizado = finalizado;
		this.reporteses = reporteses;
		this.projects = projects;
		this.usuariosProyectoses = usuariosProyectoses;
	}

	public String getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(String idProyecto) {
		this.idProyecto = idProyecto;
	}

	public String getNombreProyecto() {
		return this.nombreProyecto;
	}

	public void setNombreProyecto(String nombreProyecto) {
		this.nombreProyecto = nombreProyecto;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public Boolean getFinalizado() {
		return this.finalizado;
	}

	public void setFinalizado(Boolean finalizado) {
		this.finalizado = finalizado;
	}

	public Set<Reportes> getReporteses() {
		return this.reporteses;
	}

	public void setReporteses(Set<Reportes> reporteses) {
		this.reporteses = reporteses;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public Set<UsuariosProyectos> getUsuariosProyectoses() {
		return this.usuariosProyectoses;
	}

	public void setUsuariosProyectoses(Set<UsuariosProyectos> usuariosProyectoses) {
		this.usuariosProyectoses = usuariosProyectoses;
	}

}
