package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Reportes generated by hbm2java
 */
public class Reportes implements java.io.Serializable {

	private String idReporte;
	private Proyectos proyectos;
	private String nombre;
	private Set<Partida> partidas = new HashSet<Partida>(0);

	public Reportes() {
	}

	public Reportes(String idReporte, Proyectos proyectos) {
		this.idReporte = idReporte;
		this.proyectos = proyectos;
	}

	public Reportes(String idReporte, Proyectos proyectos, String nombre, Set<Partida> partidas) {
		this.idReporte = idReporte;
		this.proyectos = proyectos;
		this.nombre = nombre;
		this.partidas = partidas;
	}

	public String getIdReporte() {
		return this.idReporte;
	}

	public void setIdReporte(String idReporte) {
		this.idReporte = idReporte;
	}

	public Proyectos getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Proyectos proyectos) {
		this.proyectos = proyectos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Partida> getPartidas() {
		return this.partidas;
	}

	public void setPartidas(Set<Partida> partidas) {
		this.partidas = partidas;
	}

}
