package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Sesiones generated by hbm2java
 */
public class Sesiones implements java.io.Serializable {

	private Integer idSesion;
	private Usuarios usuarios;
	private Date logIn;
	private Date logOut;
	private String sessionKey;

	public Sesiones() {
	}

	public Sesiones(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Sesiones(Usuarios usuarios, Date logIn, Date logOut, String sessionKey) {
		this.usuarios = usuarios;
		this.logIn = logIn;
		this.logOut = logOut;
		this.sessionKey = sessionKey;
	}

	public Integer getIdSesion() {
		return this.idSesion;
	}

	public void setIdSesion(Integer idSesion) {
		this.idSesion = idSesion;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getLogIn() {
		return this.logIn;
	}

	public void setLogIn(Date logIn) {
		this.logIn = logIn;
	}

	public Date getLogOut() {
		return this.logOut;
	}

	public void setLogOut(Date logOut) {
		this.logOut = logOut;
	}

	public String getSessionKey() {
		return this.sessionKey;
	}

	public void setSessionKey(String sessionKey) {
		this.sessionKey = sessionKey;
	}

}
