package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

/**
 * UsuariosProyectos generated by hbm2java
 */
public class UsuariosProyectos implements java.io.Serializable {

	private UsuariosProyectosId id;
	private Proyectos proyectos;
	private Usuarios usuarios;

	public UsuariosProyectos() {
	}

	public UsuariosProyectos(UsuariosProyectosId id, Proyectos proyectos, Usuarios usuarios) {
		this.id = id;
		this.proyectos = proyectos;
		this.usuarios = usuarios;
	}

	public UsuariosProyectosId getId() {
		return this.id;
	}

	public void setId(UsuariosProyectosId id) {
		this.id = id;
	}

	public Proyectos getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Proyectos proyectos) {
		this.proyectos = proyectos;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
