package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

/**
 * UsuariosProyectosId generated by hbm2java
 */
public class UsuariosProyectosId implements java.io.Serializable {

	private String idProyecto;
	private String idUsuario;

	public UsuariosProyectosId() {
	}

	public UsuariosProyectosId(String idProyecto, String idUsuario) {
		this.idProyecto = idProyecto;
		this.idUsuario = idUsuario;
	}

	public String getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(String idProyecto) {
		this.idProyecto = idProyecto;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariosProyectosId))
			return false;
		UsuariosProyectosId castOther = (UsuariosProyectosId) other;

		return ((this.getIdProyecto() == castOther.getIdProyecto()) || (this.getIdProyecto() != null
				&& castOther.getIdProyecto() != null && this.getIdProyecto().equals(castOther.getIdProyecto())))
				&& ((this.getIdUsuario() == castOther.getIdUsuario()) || (this.getIdUsuario() != null
						&& castOther.getIdUsuario() != null && this.getIdUsuario().equals(castOther.getIdUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProyecto() == null ? 0 : this.getIdProyecto().hashCode());
		result = 37 * result + (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		return result;
	}

}
