package mx.tiid.smartconstruction.model;
// Generated 27-feb-2016 12:36:04 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private String idUsuario;
	private RolUsuarios rolUsuarios;
	private String nombres;
	private String apaterno;
	private String amaterno;
	private String password;
	private String usuario;
	private Boolean activo;
	private Set<Actividades> actividadeses = new HashSet<Actividades>(0);
	private Set<UsuariosProyectos> usuariosProyectoses = new HashSet<UsuariosProyectos>(0);
	private Set<Sesiones> sesioneses = new HashSet<Sesiones>(0);
	private Set<Comentarios> comentarioses = new HashSet<Comentarios>(0);

	public Usuarios() {
	}

	public Usuarios(String idUsuario, RolUsuarios rolUsuarios) {
		this.idUsuario = idUsuario;
		this.rolUsuarios = rolUsuarios;
	}

	public Usuarios(String idUsuario, RolUsuarios rolUsuarios, String nombres, String apaterno, String amaterno,
			String password, String usuario, Boolean activo, Set<Actividades> actividadeses,
			Set<UsuariosProyectos> usuariosProyectoses, Set<Sesiones> sesioneses, Set<Comentarios> comentarioses) {
		this.idUsuario = idUsuario;
		this.rolUsuarios = rolUsuarios;
		this.nombres = nombres;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.password = password;
		this.usuario = usuario;
		this.activo = activo;
		this.actividadeses = actividadeses;
		this.usuariosProyectoses = usuariosProyectoses;
		this.sesioneses = sesioneses;
		this.comentarioses = comentarioses;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public RolUsuarios getRolUsuarios() {
		return this.rolUsuarios;
	}

	public void setRolUsuarios(RolUsuarios rolUsuarios) {
		this.rolUsuarios = rolUsuarios;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public Set<Actividades> getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(Set<Actividades> actividadeses) {
		this.actividadeses = actividadeses;
	}

	public Set<UsuariosProyectos> getUsuariosProyectoses() {
		return this.usuariosProyectoses;
	}

	public void setUsuariosProyectoses(Set<UsuariosProyectos> usuariosProyectoses) {
		this.usuariosProyectoses = usuariosProyectoses;
	}

	public Set<Sesiones> getSesioneses() {
		return this.sesioneses;
	}

	public void setSesioneses(Set<Sesiones> sesioneses) {
		this.sesioneses = sesioneses;
	}

	public Set<Comentarios> getComentarioses() {
		return this.comentarioses;
	}

	public void setComentarioses(Set<Comentarios> comentarioses) {
		this.comentarioses = comentarioses;
	}

}
